### ISSUE TITLE
Mate Desktop update

### ISSUE THREAD

**Issue by hype3** [getsolus/packages#2125] opened 2024-04-04 16:45 UTC
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

mate-themes

### Version

 3.22.25 

### Reason for updating

latest for mate desktop

**Comment by davidjharder** [comment] 2024-04-04 16:56
Duplicate of #2124

**Closed by davidjharder** 2024-04-04 16:56 UTC
Labels: Package Update Request
