### ISSUE TITLE
Segmentation Fault when using openfortivpn

### ISSUE THREAD

**Issue by pmaccarron** [getsolus/packages#3651] opened 2024-08-22 10:37 UTC
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I receive a segmentation fault when trying to use openfortivpn v1.22.1.

### Steps to reproduce

`$ sudo openfortivpn -v VPN`

### Expected result

It should try to connect to the VPN.

### Actual result

`DEBUG:  openfortivpn 1.22.1`
`DEBUG:  revision unavailable`
`Segmentation fault`

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

```
System:
  Host: lattitude7290 Kernel: 6.9.12-297.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.1.4 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Dell product: Latitude 7290 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 09386V v: A00 serial: <superuser required> UEFI: Dell
    v: 1.9.2 date: 04/03/2019
Battery:
  ID-1: BAT0 charge: 27.8 Wh (98.2%) condition: 28.3/60.0 Wh (47.1%)
CPU:
  Info: quad core Intel Core i7-8650U [MT MCP] speed (MHz): avg: 900
    min/max: 400/4200
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: Microdia Integrated_Webcam_HD driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.2 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
    resolution: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.6
    renderer: Mesa Intel UHD Graphics 620 (KBL GT2)
Network:
  Device-1: Intel Ethernet I219-LM driver: e1000e
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi
Drives:
  Local Storage: total: 476.94 GiB used: 325.68 GiB (68.3%)
Info:
  Memory: total: 16 GiB available: 15.5 GiB used: 4.27 GiB (27.5%)
  Processes: 251 Uptime: 10m Shell: Bash inxi: 3.3.35
```

**Comment by ReillyBrogan** [comment] 2024-09-12 23:43
Duplicate of #2947

**Closed by ReillyBrogan** 2024-09-12 23:43 UTC
Labels: Bug

**Comment by TraceyC77** [comment] 2026-04-21 21:01
Are you still seeing crashes with the current version of openfortivpn, which is 1.22.1? If so, we need a backtrace in order to investigate. This is either a packaging issue or a bug in the software that needs to be resolved upstream. Thanks.

**Comment by pmaccarron** [comment] 2026-04-22 09:08
Yes, I get a "segmentation fault" as soon as I run it:
```
$ sudo openfortivpn ulssl.ul.ie
Segmentation fault 
```
My work VPN has changed recently though so and it does not seem possible to use openfortivpn for it any more due to this: 
https://www.reddit.com/r/fortinet/comments/1k0tny8/sslvpn_tunnelmode_is_being_completely_removed_in/

**Comment by TraceyC77** [comment] 2026-04-22 14:53
There are other reports on the openfortivpn tracker about segmentation faults as well. This doesn't appear to be a packaging issue. It's a code problem the openfortivpn developers will need to fix. Take a look at their tracker. If there isn't already an open issue for this, you can create one here:

https://github.com/adrienverge/openfortivpn/issues

Thanks.
