### ISSUE TITLE
Testing Discover - Error message when the app starts

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1448] opened 2024-01-27 12:04 UTC
### Summary

I've created a clone of my Plasma VM for use in testing Discover.  I did a full update using unstable, then installed Discover.

When I launch the application, before I do anything else at all, this error message displays:
![image](https://github.com/getsolus/packages/assets/6805994/f01ca6e4-abd5-4465-836c-8f68f76d3b12)

Because the expected result and actual result are obvious, I'll skip those fields in this report.

### Steps to reproduce

1. Install Discover on a Plasma machine - either virtual or hardware.
2. Launch Discover.  

### Expected result

N/A

### Actual result

N/A

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

![image](https://github.com/getsolus/packages/assets/6805994/81ed3122-8a23-442d-892d-16fc53cdc028)

**Comment by WetGeek** [comment] 2024-01-27 12:34
Because I thought the missing file might compromise further testing, I installed it using eopkg.  That installation caused 22 total packages to be downloaded and installed.  I then shut down Discover and restarted it, and that time there was no such error message displayed.

**Comment by ermo** [comment] 2024-02-02 18:32
Thanks for the report.

Discover is not ready for user testing yet, so please hold your fire until told otherwise. Thanks. :sweat_smile:

**Comment by TraceyC77** [comment] 2024-04-15 21:31
Closing as I can't reproduce at this time.

**Closed by TraceyC77** 2024-04-15 21:31 UTC
Labels: Bug, Plumbing, Confirmed, Priority: Normal
