### ISSUE TITLE
updated darktable

### ISSUE THREAD

**Issue by Atriaze** [getsolus/packages#1218] opened 2024-01-07 11:01 UTC
### Name

darktable

### Version

4.6

### Link to the release notes or announcement.

 https://github.com/darktable-org/darktable/releases/tag/release-4.6.0

### Reason for updating

The Sigmoid module now includes a new primary section.

**Comment by algent-al** [comment] 2024-01-07 12:39
Duplicate of #1189

**Closed by algent-al** 2024-01-07 12:39 UTC
Labels: Package Update Request
