### ISSUE TITLE
LenovoLegionLinux

### ISSUE THREAD

**Issue by youswer79** [getsolus/packages#4501] opened 2024-12-02 16:23 UTC
### Please confirm there isn't an open request for this package

- [X] I have searched through package addition requests

### Homepage

https://github.com/johnfanv2/LenovoLegionLinux

### Maintainer

- [ ] Would you like to be the maintainer for this package?

### Why should this be included in the repository?

Hi guys. How about this? How install it for Solus?
On Arch every work fine. And Nobara it have.

### What kind of user will use this package, and how many users do you think will use this package?

Lenovo Legion users

### Link to source archive file

https://github.com/johnfanv2/LenovoLegionLinux/archive/refs/heads/main.zip

**Comment by youswer79** [comment] 2024-12-02 16:25
I hope for Best Solus!

**Comment by GZGavinZhao** [comment] 2024-12-04 15:23
Duplicate of #2590. I'm already using it (and it works well on my Legion 5 15ACH6A) but I need to convert it to a package that I can submit. I'll try to do that in the next few days.

While you wait for the package to be added, you can install it (very easily) by yourself! I assume you're on `linux-current` (run `uname -r` and check if the output contains the string "current"). Then, install `linux-current-headers`, and following the instruction here: https://github.com/johnfanv2/LenovoLegionLinux/tree/main?tab=readme-ov-file#permanent-install-instruction Just run the two commands it shows and you're done. You don't need to build and test as I've already confirmed it will not break your system.

Note that this only provides the kernel modules so you can e.g. switch your power profiles. If you're looking for the `legion_cli` or the GUI, then it's more complicated and you should wait for the official package.

I'm closing this issue as this is a duplicate. If you need further support, please post on the Solus forum (https://discuss.getsol.us/) and mention me. My username on the forum is the same as my GitHub username.

**Closed by GZGavinZhao** 2024-12-04 15:23 UTC
Labels: Package: Addition Request, Priority: Wishlist
