### ISSUE TITLE
Solus installation failed because of unclear error on Virtualbox

### ISSUE THREAD

**Issue by JuraLys** [getsolus/packages#1660] opened 2024-02-18 03:28 UTC
see log https://termbin.com/8sw2
=== START CALAMARES 3.2.62
2024-02-18 - 04:40:15 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "Не вдалося завершити виконання зовнішньої команди."
![solus-inst-err(](https://github.com/getsolus/solbuild/assets/146434286/19910598-9c99-4915-9c71-592cf1b77a32)

**Comment by TraceyC77** [comment] 2024-02-19 19:11
Translation

> External command could not complete

Can you please provide the English translation of the text in the white area of the error dialog in the screenshot? Thanks.

**Comment by JuraLys** [comment] 2024-02-19 23:09
> Translation
> 
> > External command could not complete
> 
> Can you please provide the English translation of the text in the white area of the error dialog in the screenshot? Thanks.
cannot complete command ... for 30 seconds
in result of command run did not get otput data

**Comment by Staudey** [comment] 2024-11-25 23:46
This is the same bug as https://github.com/getsolus/packages/issues/4050

**Comment by HarveyDevel** [comment] 2024-11-25 23:58
Duplicate of #4050

**Closed by HarveyDevel** 2024-11-25 23:58 UTC
Labels: Bug, Topic: Installation
