### ISSUE TITLE
Invalid desktop files reported by `menulibre`

### ISSUE THREAD

**Issue by algent-al** [getsolus/packages#331] opened 2023-09-12 19:58 UTC
### Summary

`menulibre` is  reporting many invalid desktop files.
![menulibre](https://github.com/getsolus/packages/assets/46356616/78a305aa-6859-4a1e-a7e3-a8e5f351dea1)

This is because these desktop files are installed by one package and the executables are in another one which is not installed in the system.

In details:
`/usr/share/applications/kcm_trash.desktop` is part of `kio` package, while `/usr/bin/kcmshell5` file is part of `kde-cli-tools` package. (Maybe `kio` needs `kde-cli-tools` as rundep).
`/usr/share/applications/assistant6/` and `/usr/share/applications/linguist6` are part of  `qt6-tools ` package, while `/usr/bin/assistant6` and `/usr/bin/linguist6` and icons too are part of `qt6-tools-devel`. 

### Steps to reproduce

Run `menulibre` and click "Details" button in the error bar "Invalid desktop files detected! Please see details."

### Expected result

No errors

### Actual result

`menulibre` complaining about invalid desktop files.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Budgie

### System details

OS: Solus x86_64
Host: CELSIUS W530
CPU: Intel Xeon E3-1271 v3 (8) @ 4.000GHz
GPU: NVIDIA Quadro M2000
Memory: 15923MiB

**Comment by ermo** [comment] 2024-05-04 00:54
@algent-al I can't reproduce this for plasma6 -- can you?

**Comment by algent-al** [comment] 2024-05-04 20:05
@ermo I can't reproduce this for budgie too. Looks like it's been resolved after recent changes.

**Comment by ermo** [comment] 2024-05-05 00:45
Closing per algent's comments.

**Closed by ermo** 2024-05-05 00:45 UTC
Labels: Bug
