### ISSUE TITLE
#1448 Testing Discover - After un-installing an application, an error message displays.

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1450] opened 2024-01-27 14:18 UTC
### Summary

While testing  Discover, I used it to install KMyMoney.  After finding an error in that application and creating an incident report (#1448), I wanted to test using Discover to remove the application I had used it to install.  When I did that, apparently the command succeeded, however an error messaage was displayed.

### Steps to reproduce

1. On a VM, I used Discover to install an application that was not already present, KMyMoney.
2. After exercising that app, it came time to remove it, again using Discove, so I clicked the link at the top to do that.

### Expected result

I expected the application to be removed, perhaps also including the dependencies that had been installed along with it.

### Actual result

![image](https://github.com/getsolus/packages/assets/6805994/90417f36-ab97-4c88-9430-20efff2bcc55)
 
Since I had just used Discover to remove this application, its absence is not really an error.

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

![image](https://github.com/getsolus/packages/assets/6805994/a269c4ca-1e5f-4ab5-b631-a7630f7422da)

### Other comments

After using Discover to remove KMyMoney, I ran `eopkg rmo` in order to see whether Discover had removed the dependencies it had installed along with the application.  Clearly it had not, as there were 20+ orphan packages that could only be those dependencies.  I used `eopkg rmo` to remove them.  I don't know whether this is expected behavior from Discover.

**Comment by TraceyC77** [comment] 2024-04-15 21:57
Re-tested with a flatpak (CudaText - had installed previously) and a native package (SpeedCrunch - installed, restarted Discover, and uninstalled)

Both programs uninstalled without any errors
Closing since I can't reproduce at this time.

**Closed by TraceyC77** 2024-04-15 21:57 UTC
Labels: Bug
