### ISSUE TITLE
CUPS Open Printing package is outdated

### ISSUE THREAD

**Issue by StasSche** [getsolus/packages#2422] opened 2024-04-28 10:29 UTC
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

CUPS

### Version

2.4.8

### Link to the release notes or announcement.

https://github.com/OpenPrinting/cups/releases/tag/v2.4.8

### Reason for updating

The version used in SOLUS is mid-2019. For example, even Debian 11 "Bullseye" uses newer versions. It creates problems with using CUPS enabled printers (like 90% of the market): for example, my printer is discoverable by SOLUS version of CUPS (2.2.13), but it prints incorrectly.

**Comment by malfisya** [comment] 2024-04-28 13:13
There is already task for this https://github.com/getsolus/packages/issues/1312 . It is planned for 4.6 release. Also please refrain using such adjective (hoplessly), it doesn't sound nice.  "Very" is good and understandable. Cheers!

**Comment by ReillyBrogan** [comment] 2024-04-28 20:05
I've actually got this set of package updates ready to go and it should go into unstable this week.

**Comment by TraceyC77** [comment] 2024-04-28 22:56
Closing as a duplicate of 1312

**Closed by TraceyC77** 2024-04-28 22:56 UTC
Labels: Package Update Request
