### ISSUE TITLE
Solus repo unbearibly slow

### ISSUE THREAD

**Issue by Test-Account666** [getsolus/packages#4141] opened 2024-10-23 19:22 UTC
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

Not sure where to inform you about this, so I guess I'll just do it here.

For quite a while now, the Solus repo has been *very* slow.

It's basically unbearable to even update packages.

An example:
![grafik](https://github.com/user-attachments/assets/36e56f3a-db00-4a4a-bdca-c3ef69e6643c)

### Steps to reproduce

1. Try updating or installing basically any application

### Expected result

Packages are installed at a reasonable speed

### Actual result

Packages that should take seconds to install require minutes

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Plasma

### System details

System:
  Host: TestAccount666-PC Kernel: 6.10.13-304.current arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.1.5 Distro: Solus 4.5 resilience
Machine:
  Type: Desktop Mobo: ASRock model: Z690 Extreme serial: <superuser required>
    UEFI: American Megatrends LLC. v: 19.02 date: 08/09/2024
CPU:
  Info: 12-core (8-mt/4-st) 12th Gen Intel Core i7-12700K [MST AMCP]
    speed (MHz): avg: 800 min/max: 800/4900:5000:3800
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 21 [Radeon RX 6900 XT]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.3 driver:
    gpu: amdgpu resolution: 1: 1920x1080 2: 1920x1080
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.3 renderer: AMD
    Radeon RX 6900 XT (radeonsi navi21 LLVM 18.1.8 DRM 3.57
    6.10.13-304.current)
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e
  Device-2: Realtek RTL8125 2.5GbE driver: r8169
Drives:
  Local Storage: total: 12.74 TiB used: 1.43 TiB (11.2%)
Info:
  Memory: total: 96 GiB note: est. available: 94.05 GiB
    used: 15.31 GiB (16.3%)
  Processes: 430 Uptime: 8h 48m Shell: Bash inxi: 3.3.36

**Comment by Staudey** [comment] 2024-10-23 19:48
Are you behind a VPN?

**Comment by Test-Account666** [comment] 2024-10-25 15:15
> Are you behind a VPN?

Nope. No VPN. Internet speeds are perfectly fine for the rest of my system. Only the Solus Repo has that problem

**Comment by Staudey** [comment] 2024-10-25 23:08
Anything else special about your network connection?

This sounds a lot like an issue a small number of people experience on their systems from time to time, but as far as I know nobody has been able to figure out the cause yet.

Example:
https://www.reddit.com/r/SolusProject/comments/14xbvhy/eopkg_super_slow/

**Comment by Test-Account666** [comment] 2024-10-26 22:17
> Anything else special about your network connection?
> 
> This sounds a lot like an issue a small number of people experience on their systems from time to time, but as far as I know nobody has been able to figure out the cause yet.
> 
> Example: https://www.reddit.com/r/SolusProject/comments/14xbvhy/eopkg_super_slow/

No, I don't see anything special with my network connection...

Neither physically nor software wise

**Comment by wvpianoman** [comment] 2024-10-27 02:48
I had issues with the Solus repos.  Solus would work great in a VM, but not on bare metal.   It turned out to be something with my router.  I switched routers and no issues at all.

I suggest you try installing Solus in a VM and see if it can update correctly.

I know this is no real answer, but it is what I've personally experienced.

**Comment by TraceyC77** [comment] 2024-10-28 01:55
The package repo is behind CDN. it's been allowing downloads at normal speed here. This is not a problem with the CDN, it's a networking problem between the CDN and your machine.

The most likely cause, that we've seen with other users, is a slowdown somewhere in the route between your machine and the CDN. Please reach out to us on Matrix so we can troubleshoot this with you. 

As a first step, can you copy and pasate the results of this? You can install mtr from our repositories if you don't already have it installed.

```
mtr cdn.getsol.us

**Comment by Test-Account666** [comment] 2024-10-28 10:42
> The package repo is behind CDN. it's been allowing downloads at normal speed here. This is not a problem with the CDN, it's a networking problem between the CDN and your machine.
> 
> The most likely cause, that we've seen with other users, is a slowdown somewhere in the route between your machine and the CDN. Please reach out to us on Matrix so we can troubleshoot this with you.
> 
> As a first step, can you copy and pasate the results of this? You can install mtr from our repositories if you don't already have it installed.
> 
> ```
> mtr cdn.getsol.us
> ```

I was able to install packages at proper speed yesterday. I didn't test today though.

![mtr](https://github.com/user-attachments/assets/4176a63a-4f5d-49a0-bc1e-dd53a6f25ed5)

**Comment by TraceyC77** [comment] 2024-10-29 01:35
Thanks for the update. Those results tell me two things. The issue is not due to our infrastructure or the Solus installation.
Based on that mtr output, there is a local network problem at hope 3, which might be in your local network.

Since this isn't a problem we can fix, I'm closing this out. Feel free to chat with us on Matrix.

**Closed by TraceyC77** 2024-10-29 01:35 UTC
