### ISSUE TITLE
Mate Desktop update

### ISSUE THREAD

**Issue by hype3** [getsolus/packages#2126] opened 2024-04-04 16:49 UTC
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

mate-calc

### Version

1.28.0

### Link to the release notes or announcement.

https://github.com/mate-desktop/mate-calc/releases/tag/v1.28.0

### Reason for updating

latest for mate desktop

**Comment by davidjharder** [comment] 2024-04-04 16:57
Duplicate of #2124

**Closed by davidjharder** 2024-04-04 16:57 UTC
Labels: Package Update Request
