### ISSUE TITLE
Budgie Lockscreen Keyboard Input locks users out of profile  (T3450)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#254] opened 2023-08-16 22:25 UTC
<div dir="rtl"><b>Solusitor</b>&nbsp;(<em>&#35;solusitor</em>),&nbsp;2017-04-24&nbsp;12:28:00&nbsp;UTC</div><br/>

I'm on an old 2012 Samsung NP300E5Z laptop. I installed the newest Solus Budgie only a few days ago. I updated yesterday and tried to recreate this bug multiple times, it happens every single time. 

If you set your keyboard input to non-Latin alphabet language (Asian languages, Indian, Russian, Bulgarian, etc.), and then Suspend or Lock the OS, you get locked out. 

Keyboard input cannot be changed when trying to enter password, neither with the key combination you have set up, nor with a graphic button on the screen (there isn't one). Password comes back as invalid every time, because it's not written in Roman letters. The only way to get out of this is to turn the computer off completely and lose any unsaved data.

The same thing doesn't happen when you Restart, I assume because you are not yet logged into your profile and it goes to default keyboard input (English). Password is entered successfully, and once logged in, it remembers you'd set the second language input and goes back to it, and if you Suspend or Lock again, you get stuck in the same loop. 

This is a serious issue and can affect anyone who does not use a Latin alphabet at all times. Important data could be lost.

**Comment by TraceyC77** [comment] 2023-09-28 21:44
Closing this issue due to age and lack of updates, after being unable to reproduce. If this is still an issue for anyone, please open a new bug on our tracker.

**Closed by TraceyC77** 2023-09-28 21:44 UTC
Labels: Software, Priority: Normal
