### ISSUE TITLE
Corrupt file when verify integrity flatpak during eopkg check

### ISSUE THREAD

**Issue by PennyFarthing-GH** [getsolus/packages#1038] opened 2023-12-17 17:46 UTC
### Summary

After the sync updates for week 50,2023, the result of the terminal command `**[eopkg_check_20231215.txt](https://github.com/getsolus/packages/files/13697177/eopkg_check_20231215.txt)**` shows an error:

```
Vérification de l'intégrité de flatpak                                        Cassé
Fichier corrompu : usr/lib/tmpfiles.d/flatpak.conf

```
Please note that I didn't have this error with the previous update (week 49,2023).

### Steps to reproduce

By the terminal command sudo eopkg check

### Expected result

I expected to see that integrity packages was OK.

### Actual result

It was OK, except for package `flatpak`.
[eopkg_check_20231215.txt](https://github.com/getsolus/packages/files/13697215/eopkg_check_20231215.txt)

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

This sync update went off without a hitch, and packages installed via flatpak seem to launch normally.
It's just the error in the terminal command `sudo eopkg check` which caught my attention, that's the reason why I have open a bug in Solus tracker as suggested.

**Comment by HarveyDevel** [comment] 2023-12-17 23:44
Duplicate of #1035

**Closed by HarveyDevel** 2023-12-17 23:44 UTC
Labels: Bug
