### ISSUE TITLE
LibreCAD won't open

### ISSUE THREAD

**Issue by mtslo** [getsolus/packages#334] opened 2023-09-15 10:59 UTC
### Summary

Dear Solus Team,

 I am writing to you as I've been encountering some issues with LibreCAD. Whenever I attempt to open the application by clicking on the icon, it fails to launch. When I try starting the application from the terminal, I receive following error message:

```
→ librecad          
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: cannot register existing type 'GdkDisplayManager'

(librecad:3426): GLib-CRITICAL **: 12:41:40.973: g_once_init_leave: assertion 'result != 0' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: invalid (NULL) pointer instance

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: invalid (NULL) pointer instance

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.976: cannot register existing type 'GdkDisplay'

(librecad:3426): GLib-CRITICAL **: 12:41:40.976: g_once_init_leave: assertion 'result != 0' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.976: g_type_register_static: assertion 'parent_type > 0' failed

(librecad:3426): GLib-CRITICAL **: 12:41:40.976: g_once_init_leave: assertion 'result != 0' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.976: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
[1]    3426 segmentation fault (core dumped)  librecad
```

### Steps to reproduce

Start LibreCAD application from desktop launcher or from the terminal.

### Expected result

The application should open and be ready for use.

### Actual result

```
→ librecad          
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: cannot register existing type 'GdkDisplayManager'

(librecad:3426): GLib-CRITICAL **: 12:41:40.973: g_once_init_leave: assertion 'result != 0' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: invalid (NULL) pointer instance

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: invalid (NULL) pointer instance

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.973: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.976: cannot register existing type 'GdkDisplay'

(librecad:3426): GLib-CRITICAL **: 12:41:40.976: g_once_init_leave: assertion 'result != 0' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.976: g_type_register_static: assertion 'parent_type > 0' failed

(librecad:3426): GLib-CRITICAL **: 12:41:40.976: g_once_init_leave: assertion 'result != 0' failed

(librecad:3426): GLib-GObject-CRITICAL **: 12:41:40.976: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
[1]    3426 segmentation fault (core dumped)  librecad
```

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

`    Device name: solus

  Hardware Model: Apple Inc. Macmini5,2
          Memory: 8,0GiB
       Processor: Intel® Core™ i5-2520M × 4
        Graphics: AMD TURKS
   Disk Capacity: 512,1GB

  Budgie Version: 10.8
         OS Name: Solus 4.4 Harmony
         OS Type: 64-bit
Windowing System: X11
  Kernel Version: Linux 6.4.15-254.current`

**Comment by davidjharder** [comment] 2023-09-20 23:54
I can't reproduce this with 2.2.0.1 (currently in Stable) or 2.2.0.2 (currently in Unstable)

mtslo: Can you please try again when 2.2.0.2 gets to Stable (probably Friday) and report back?

**Comment by mtslo** [comment] 2023-09-23 04:16
Hi davidjharder,

Unfortunately, the error persists despite the recent update.
I found something similar on libreCAD GitHub issues page, but developer said that this was already fixed (June 2020) in following releases --> [LibreCAD crashed on opening DXF from file browser or CLI](https://github.com/LibreCAD/LibreCAD/issues/1250 )

```zsh
→ eopkg info librecad
Installed package:
Name                : librecad, version: 2.2.0.2, release: 13
Summary             : LibreCAD is a free Open Source CAD application for Windows, Apple and Linux
Description         : LibreCAD is a 2D CAD drawing tool based on the community edition of QCAD. LibreCAD uses the cross-platform
                      framework Qt, which means it works with most operating systems.
Licenses            : GPL-2.0-or-later
Component           : office
Dependencies        : libstdc++ muparser libgcc freetype2 qt5-base glibc qt5-svg 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 62.83 MB
Reverse Dependencies: 

Package found in Solus repository:
Name                : librecad, version: 2.2.0.2, release: 13
Summary             : LibreCAD is a free Open Source CAD application for Windows, Apple and Linux
Description         : LibreCAD is a 2D CAD drawing tool based on the community edition of QCAD. LibreCAD uses the cross-platform
                      framework Qt, which means it works with most operating systems.
Licenses            : GPL-2.0-or-later
Component           : office
Dependencies        : libstdc++ muparser libgcc freetype2 qt5-base glibc qt5-svg 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 62.83 MB, Package Size: 5.48 MB
Reverse Dependencies: librecad-dbginfo

→ librecad           
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
QLayout: Attempting to add QLayout "" to QG_LibraryWidget "Library", which already has a layout

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.307: cannot register existing type 'GdkDisplayManager'

(librecad:27968): GLib-CRITICAL **: 06:11:25.307: g_once_init_leave: assertion 'result != 0' failed

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.307: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.307: invalid (NULL) pointer instance

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.307: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.307: invalid (NULL) pointer instance

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.307: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.311: cannot register existing type 'GdkDisplay'

(librecad:27968): GLib-CRITICAL **: 06:11:25.311: g_once_init_leave: assertion 'result != 0' failed

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.311: g_type_register_static: assertion 'parent_type > 0' failed

(librecad:27968): GLib-CRITICAL **: 06:11:25.311: g_once_init_leave: assertion 'result != 0' failed

(librecad:27968): GLib-GObject-CRITICAL **: 06:11:25.311: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
[1]    27968 segmentation fault (core dumped)  librecad
```

**Comment by algent-al** [comment] 2023-09-23 16:18
Hi @mtslo. Please try to check for broken packages:
`sudo eopkg check | tee /dev/stderr | grep Broken | awk '{print $4}' | xargs sudo eopkg it --reinstall`
Even if doesn't find any "Broken"  packages I suggest to reinstall these packages:
`sudo eopkg it --reinstall glib2 glib2-32bit`

**Comment by mtslo** [comment] 2023-10-01 06:35
Hi @algent-al,

Thanks for your proposals, but unfortunately issue remain, even after checking and reinstalling suggested packages.

**Comment by Justinzobel** [comment] 2024-02-10 07:22
Can you please try it with a new user account, sometimes config options can cause issues with starting software?

**Comment by ermo** [comment] 2024-05-04 00:48
I cannot reproduce this, so closing.

**Closed by ermo** 2024-05-04 00:48 UTC
Labels: Invalid
