### ISSUE TITLE
Sleep quality problems since updating the kernel from 5.0 to 6.5 (T8345)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#80] opened 2023-08-16 15:40 UTC
<div dir="rtl"><b>Dzmitry&nbsp;Malyshau</b>&nbsp;(<em>&#35;kvark</em>),&nbsp;2019-09-16&nbsp;20:31:44&nbsp;UTC</div><br/>

I noticed that after one big update a month or two ago my laptop stopped sleeping well: it would run out of battery while sleeping overnight.

Laptop: Thinkpad X1 Extreme (1st revision)
Using Nvidia proprietary driver for the GPU.

See the update history in {F5145460}

It ends with the suspected large update that moves the kernel from version 5.0 to 5.2.

Any ideas on the known upstream issues to track, or the ways to investigate this, would be highly appreciated! Please let me know if I can provide more info.

**Comment by TraceyC77** [comment] 2023-09-23 21:22
I am able to reproduce this issue with kernel 6.5.3-256.current

System: Dell XPS 9710 with hybrid Nvidia dedicated / Intel internal GPUs
nVidia proprietary drivers installed through Hardware Drivers

Testing steps:
1. Charge battery to 100%
2. Put system to sleep / suspend
3. Wait 5 minutes, then resume the system

The Dell bios allows the user to select the GPU to run external displays from.
With the GPU set to nVidia, the bug can be reproduced. Battery drains significantly during suspend.
After 5 minutes, battery level was at 93%

With the GPU set to Intel, the bug cannot be reproduced. Battery drain is minimal during suspend.
After 5 minutes, battery level was at 100%. I was able to suspend the laptop overnight. In the morning, battery level was in the 90s.

## System details
❯ inxi -Fazy
System:
  Kernel: 6.5.3-256.current arch: x86_64 bits: 64 compiler: gcc v: 12.3.0
    clocksource: tsc available: acpi_pm
    parameters: initrd=\EFI\com.solus-project\initrd-com.solus-project.current.6.5.3-256
    root=PARTUUID=a7a26d35-2150-7f48-9225-78b81a6f62ea quiet loglevel=3 splash
    systemd.show_status=false rw radeon.si_support=0 radeon.cik_support=0
    amdgpu.si_support=1 amdgpu.cik_support=1 nvidia-drm.modeset=1
    nvidia.NVreg_PreserveVideoMemoryAllocations=1
    nvidia.NVreg_TemporaryFilePath=/var/tmp nvidia-drm.modeset=1
  Desktop: KDE Plasma v: 5.27.7 tk: Qt v: 5.15.10 wm: kwin_x11 vt: 2 dm: SDDM
    Distro: Solus 4.4 harmony
Machine:
  Type: Laptop System: Dell product: XPS 17 9710 v: N/A
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: Dell model: 0VG94J v: A00 serial: <superuser required> UEFI: Dell
    v: 1.19.0 date: 03/08/2023
Battery:
  ID-1: BAT0 charge: 65.2 Wh (100.0%) condition: 65.2/95.1 Wh (68.6%)
    volts: 12.6 min: 11.4 model: BYD DELL F8CPG21 type: Li-poly serial: <filter>
    status: full

**Comment by ermo** [comment] 2024-05-01 18:56
@TraceyC77 Is this still an issue on kernel 6.8?

**Comment by TraceyC77** [comment] 2024-05-02 19:07
I can confirm this is no longer an issue with 6.8.8-288.current
I will check with linux-lts today

**Comment by sheepman4267** [comment] 2024-05-03 01:40
@TraceyC77 It looks like this is an NVIDIA thing, right? I don't have an optimus laptop. Let me know if I can still help with this.

**Comment by TraceyC77** [comment] 2024-11-03 19:30
Closing, since we are no longer shipping t5hese kernels.

**Comment by TraceyC77** [comment] 2024-11-03 19:30
Closing, since we are no longer shipping these kernels.

**Closed by TraceyC77** 2024-11-03 19:30 UTC
Labels: Bug, Hardware Support, Priority: Low, Kernel
