### ISSUE TITLE
Xfce Dark Theme not recognized by some apps

### ISSUE THREAD

**Issue by WetGeek** [getsolus/packages#1616] opened 2024-02-14 16:27 UTC
### Summary

Both my Xfce laptop and Xfce VM exhibit this problem.  My Theme setting for both is a dark theme, but some applications that I use, including when I use Element, do not use the system theme.

![image](https://github.com/getsolus/packages/assets/6805994/17e49a9a-35cd-4066-8734-e39cbeab0ede)

I haven't compiled a comprehensive list of applications that don't respect the Xfce Theme setting, but I've been using Xfce as a daily driver recently, and I notice it very often.  Here's an example of it in Element.  Whatever option I select, the display is exactly the same - Light.

![image](https://github.com/getsolus/packages/assets/6805994/22a469c1-39a4-4c30-b754-858677bb663a)

### Steps to reproduce

Seledt Qogir-Dark as the Theme setting in Xfce.

### Expected result

Applications would either display using the dark theme outright, or would do so after being told to follow the system theme.

### Actual result

As I work with Xfce as a daily-driver, I've noticed that applications I'm used to seeing displayed with a dark theme are displayed with a light theme instead.  It's very noticeable, as my eyes are very sensitive to the bright while light.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

![image](https://github.com/getsolus/packages/assets/6805994/ff08ea2e-2adb-4a10-b7b0-4581115120f6)

**Comment by davidjharder** [comment] 2024-02-14 19:08
Hey @WetGeek, thanks for the report. 
Please name a few of the applications which do not properly follow the system theme.

**Comment by brent111** [comment] 2024-02-16 22:16
Can confirm. Libre Office, Firefox seem to use their own Blacks despite my efforts. It's Fri 2/16 and I just had 96 XFCE updates installed so see what happens on reboot later.

**Comment by EbonJaeger** [comment] 2024-05-08 19:35
Duplicate of #1099

**Closed by EbonJaeger** 2024-05-08 19:35 UTC
Labels: Bug, Xfce, Priority: Normal
