### ISSUE TITLE
GNOME 46: GTK4: Graphical glitches, menus appearing/disappearing slowly, windows scrambled during maximize/minimize

### ISSUE THREAD

**Issue by sebo505** [getsolus/packages#2351] opened 2024-04-21 19:16 UTC
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

I encounter all sort of graphical issues, maybe especially for gtk apps, like white flickering at window corners or in corners of search bars, menus only appearing/disappearing slowly, windows getting scrambled during maximize and minimize.
See video attached.

I have seen same behaviour on Fedora 40. Basically, I don't really know what's causing this, might also be kernel related or to my old graphics card.
Might also be related to this [issue](https://github.com/getsolus/packages/issues/1617) I posted some weeks ago.

### Steps to reproduce

Open program, such as nautilus, gnome-calculator, foliate...
observe corners
maximize, minimize window

### Expected result

no graphical glitches

### Actual result

graphical glitches ans anomalies

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

GNOME

## Berichtdetails
- **Erstellungsdatum:**                            2024-04-21 21:09:04

## Hardware-Informationen:
- **Hardware-Modell:**                             Hewlett-Packard HP EliteBook 6930p
- **Speicher:**                                    8,0 GiB
- **Prozessor:**                                   Intel® Core™2 Duo T9550  × 2
- **Grafik:**                                      AMD RV620
- **Festplattenkapazität:**                        250,1 GB

## Software-Informationen:
- **Firmware-Version:**                            68PCD Ver. F.16
- **Name des Betriebssystems:**                    Solus 4.5 Resilience
- **Betriebssystem-Build:**                        (null)
- **Betriebssystem-Typ:**                          64-bit
- **GNOME-Version:**                               46
- **Fenstermanager:**                              X11
- **Kernel-Version:**                              Linux 6.8.7-286.current

**Comment by sebo505** [comment] 2024-04-21 19:17
https://github.com/getsolus/packages/assets/65250211/74de4a52-4237-4715-ae90-4b7dde550f1d

**Comment by sebo505** [comment] 2024-04-23 04:15
This issue seems to be related to a newly introduced [GTK renderer.](https://www.phoronix.com/news/GTK-State-Of-New-Renderers)

Returning to classic OpenGL renderer by adding `GSK_RENDERER=gl` to `/etc/environment` as described [here](https://bbs.archlinux.org/viewtopic.php?id=294168) solves this issue for me in GNOME 46 on Solus as well as on Fedora 40.
Using classic OpenGL renderer is advised for older hardware, which I am using.

**Comment by ermo** [comment] 2024-04-24 12:43
@sebo505

Please provide the output of `glxinfo |grep 'profile version'`?

The upstream work is said to require OpenGL 3.3+/OpenGL ES 3.0+; if your card supports those according to the `glxinfo` output above, perhaps it might be a good idea to alert upstream to your experience given they apparently want to hear from users re. bugs/poor experiences with the new renderer?

**Comment by ReillyBrogan** [comment] 2024-04-24 20:22
There are actually two separate kernel drivers for AMD GPUs, the current one (`amdgpu`) and one for much older hardware (`radeon`). On Solus we override the kernel so that it uses the `amdgpu` driver even on old hardware as it tends to still work pretty well and is more actively developed.

Your hardware is likely old enough that it would normally be using the `radeon` driver, you could try switching back to that to see if it helps at all.

To do that:
1. `sudo mkdir -p /etc/kernel/cmdline.d/`
2. `echo "radeon.si_support=1 radeon.cik_support=1 amdgpu.si_support=0 amdgpu.cik_support=0" | sudo tee /etc/kernel/cmdline.d/radeon.conf`
3. `sudo clr-boot-manager update`

Then reboot and you should be using the `radeon` driver instead. You can test to see if the issue still exists then. If you want to switch back to the `amdgpu` driver just delete `radeon.conf` and run `sudo clr-boot-manager update` again.

**Comment by sebo505** [comment] 2024-04-24 21:44
> Please provide the output of `glxinfo |grep 'profile version'`?

Max core profile version: 3.3
Max compat profile version: 3.0
Max GLES1 profile version: 1.1
Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 24.0.6
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 24.0.6

**Comment by sebo505** [comment] 2024-04-24 21:51
> Your hardware is likely old enough that it would normally be using the `radeon` driver, you could try switching back to that to see if it helps at all.

Before I ran your commands, I ran `lspci -k | grep -EA3 'VGA|3D|Display'` to check what driver is currently in use.
Output was the following:
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV620/M82 [Mobility Radeon HD 3450/3470]`
	`Subsystem: Hewlett-Packard Company RV620/M82 [Mobility Radeon HD 3450/3470]`
	`Kernel driver in use: radeon`
`03:00.0 Network controller: Intel Corporation Ultimate N WiFi Link 5300`

Doesn't this imply that for some reason `amdgpu` actually wasn't in use?

I then ran your commands anyway. Couldn't detect any difference so far.

**Comment by ReillyBrogan** [comment] 2024-04-24 22:11
I checked the kernel sources, and I think your GPU might actually be too old for the AMDGPU driver. I didn't realize this before, but it appears that there's a range of GPUs that `radeon` supports and a range of GPUs that `amdgpu` supports and it's only in the overlapping range that `amdgpu` is preferred over `radeon` (on Solus).

I think your best bet here is to open up a GTK issue and hope the GTK devs are able to fix it.

**Comment by TraceyC77** [comment] 2024-10-28 02:21
Closing this since the problem is not something we can fix.

**Closed by TraceyC77** 2024-10-28 02:21 UTC
Labels: Bug, Upstream
